version: 0.2

phases:
  install:
    runtime-versions: 
      python: 3.8
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 962746374367.dkr.ecr.us-east-2.amazonaws.com)
      - REPOSITORY_URI=962746374367.dkr.ecr.us-east-2.amazonaws.com/test-demo
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker docker build -t test-demo .
      - docker tag test-demo:latest 962746374367.dkr.ecr.us-east-2.amazonaws.com/test-demo:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 962746374367.dkr.ecr.us-east-2.amazonaws.com/test-demo:latest